version: '3.7'
services:
  mongodb:
    image: mongo:5.0.3-focal
    container_name: mongodb
    env_file:
        - .env
    ports:
      - 27017:27017
    volumes:
      - /root/nosql/mongodb:/nosql/mongodb

volumes:
  mongodb:
