version: '3.7'
services:
  mongodb:
    image: mongo:5.0.3-focal
    container_name: mongodb
    env_file:
        - .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./mongodb:/nosql/mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  backend:
    container_name: backend
    build:
      dockerfile: backend/Dockerfile
      context: .
    command: python main.py
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongodb
    volumes:
      - ./source:/nosql/source
